### PR TITLE
Race format enhancements

### PR DESCRIPTION
**Pull request by pulquero**

### CODE REVIEW

**Comment by martinglass** [comment]
- The Lap numbers don't appear after Lap 1 on the list of laps (Run/Current etc)
- When a Pilot is "Done", the lap number and lap time etc don't get announced
- When there is a lap announcement, it delays the announcements of time remaining in the race. Time announcements are time critical and should have priority.
- To me "BQE Race Time" is 2 minutes adding 30 seconds Grace Time to finish a lap. The total race time is 2 mins 30 seconds maximum - not 2m 30s exactly.
- This shows up as follows:
    The countdown beeps play only at the end of the 30s Grace time, not before the end of the 2m Race Time.
    There isn't a beep at the end of the 2 mins Race Time either, which would happen it there was a countdown then.
    There is no announcement at the start of the Grace Period to say "Pilots complete your lap"
    There doesn't need to be a countdown for the end of the Grace Period, only an announcement to say "Race is Complete"

**Comment by pulquero** [comment]
The existing code already prioritises time announcements so i'm not sure what more can be done. Maybe we can interrupt existing phrases.

**Comment by pulquero** [comment]
Should there be a countdown for the grace period as well as normal race time?

**Comment by martinglass** [comment]
I don’t believe it’s necessary. Pilots know they’ve got grace (30secs)  to complete their lap. Most pilots will have done so before the end of the grace period. All that needs to be announced is “race completed”, either after the last pilot finishes or at the end of the grace period if not all pilots have finished. Just my opinion, based on my brief encounters at BQEs, I’m sure other views are equally valid.
________________________________

**Comment by pulquero** [comment]
I'll go with that for now then. All done!

**Comment by martinglass** [comment]
Brilliant. I’ll give it a quick test this evening.

Many thanks 🙏
________________________________

**Comment by martinglass** [comment]
Just did a quick few tests. The announcements are excellent. Well done. That's one big step forward.
However, I noticed a couple of other issues:
1) if a pilot completes his last lap after the end of the grace period, that lap is counted in the race results, when it shouldn't have counted, being "out-of-time". The announcements are all ok, but the last lap shouldn't be counted in the results.
2) this doesn't have anything to do with grace periods, but when scheduling a race, the schedule counts down and then a "wait" notice appears on the webpage, but the race doesn't start.

**Comment by pulquero** [comment]
The last lap is greyed indicating it is late, you can use the left hand + to keep it or right hand X to remove it. I assume if you do nothing, it treats it as deleted.  This is default rh behaviour.

**Comment by martinglass** [comment]
No, by default it treats one late lap and a valid one. After that it’s ok - recorded but not included in the race results by default.
________________________________

**Comment by pulquero** [comment]
Can you confirm whether your late lap that is appearing has the additional + button?

**Comment by pulquero** [comment]
I've fixed (2). When you re-test (1), can you check if there is an 'Ignoring lap after team race winner declared' message in the log. That will indicate if the server thinks it is late or not.

**Comment by martinglass** [comment]
The race format was 22 secs plus 8 secs Grace-time. Anything beyond 30 secs should not be counted.

Here's the screen shot from the Results page. You can see that the second lap was counted, even though it finished after the end of Grace-time. The Results show 2 laps, when only 1 should have been counted.

[cid:3174068f-8b9e-44b0-b658-b16e17a93a8c]

Attached are the logs, config and db files. I did get some ignore lap messages, but I think they related to other passes.

Hope this helps - ask if you need more information.

Martin

________________________________

**Comment by martinglass** [comment]
I can't see how the server can think it's a late lap, if it's been included in the Results - unless there's a flaw in the code (which I doubt).

________________________________

**Comment by martinglass** [comment]
There was a line in the logs saying "ignored lap", but this was because I let the race continue to see what would happen to the next pass.
2021-09-14 22:41:51.316: __main__ [INFO] Ignoring lap after team race winner declared: Node=2, lap=3, lapTime=0:08.809

The server didn't ignore Lap 2 which was a 24.765s lap, but it did ignore the subsequent lap, which was the 8.808s lap shown in the logfile.

________________________________

**Comment by martinglass** [comment]
Well done 👏👏👏

________________________________

**Pull request merged**
